Connect Mysql log success
Create Table ROSLog Success
Create Table ROSLog Success
Starting Parse ROS Log
ROS Log Match Failed: [0m[ INFO] [1619938430.070822262]: advertised as /vesc/low_level/ackermann_cmd_mux/input/navigation
ROS Log Match Failed: [0m
ROS Log Match Failed: Press Ctrl-C to interrupt
ROS Log Match Failed: log file: /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/racecar_spawn-4*.log
ROS Log Match Failed: log file: /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/keyboard_teleop-19*.log
ROS Log Match Failed: [0m[ INFO] [1619938429.209254195]: Initializing nodelet with 4 worker threads.[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.321988522]: AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/low_level_mux.yaml][0m
Insert Row to Table ROSLog Failed
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
ROS Log Match Failed:     self.read_header()
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
ROS Log Match Failed:     self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
ROS Log Match Failed:     d = sock.recv(buff_size)
ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: 
Insert Row to Table ROSLog Failed
ROS Log Match Failed: 
ROS Log Match Failed: 
ROS Log Match Failed: 0.000000000  Node Startup
ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout] waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.
ROS Log Match Failed: 0.000000000 INFO /vesc/low_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout] waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.
ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux_nodelet_manager [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/loader.cpp:233(Loader::Impl::advertiseRosApi)] [topics: /rosout] Initializing nodelet with 4 worker threads.
ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux_nodelet_manager [/home/liike/ROS/src/racecar/system/racecar/ackermann_cmd_mux/src/ackermann_cmd_mux_nodelet.cpp:181(AckermannCmdMuxNodelet::reloadConfiguration)] [topics: /rosout, /vesc/high_level/ackermann_cmd_mux/parameter_descriptions, /vesc/high_level/ackermann_cmd_mux/parameter_updates, /vesc/high_level/ackermann_cmd_mux/output] AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/high_level_mux.yaml]
ROS Log Match Failed: 0.000000000 INFO /vesc/low_level/ackermann_cmd_mux_nodelet_manager [/home/liike/ROS/src/racecar/system/racecar/ackermann_cmd_mux/src/ackermann_cmd_mux_nodelet.cpp:181(AckermannCmdMuxNodelet::reloadConfiguration)] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux/parameter_descriptions, /vesc/low_level/ackermann_cmd_mux/parameter_updates, /vesc/low_level/ackermann_cmd_mux/output] AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/low_level_mux.yaml]
ROS Log Match Failed: 0.000000000 INFO /vesc/mux_chainer [/tmp/binarydeb/ros-melodic-topic-tools-1.14.10/src/relay.cpp:101(MessageEvent<topic_tools::ShapeShifter>&))] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux/input/navigation] advertised as /vesc/low_level/ackermann_cmd_mux/input/navigation
ROS Log Match Failed: 
ROS Log Match Failed: 0.000000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:80(service::exists)] [topics: /rosout] waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
ROS Log Match Failed: 0.000000000 INFO /gazebo_gui [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:80(service::exists)] [topics: /rosout] waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
ROS Log Match Failed: 0.000000000 INFO /racecar_spawn [gazebo_interface.py:27(spawn_urdf_model_client)] [topics: /clock, /rosout] Waiting for service /gazebo/spawn_urdf_model
ROS Log Match Failed: 0.000000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states] waitForService: Service [/gazebo/set_physics_properties] is now available.
ROS Log Match Failed: 0.019000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-2.8.7/src/gazebo_ros_api_plugin.cpp:2334(GazeboRosApiPlugin::physicsReconfigureThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Physics dynamic reconfigure ready.
ROS Log Match Failed: 0.000000000 INFO /better_odom [/tmp/binarydeb/ros-melodic-topic-tools-1.14.10/src/relay.cpp:101(MessageEvent<topic_tools::ShapeShifter>&))] [topics: /rosout, /pf/pose/odom] advertised as /pf/pose/odom
ROS Log Match Failed: 
ROS Log Match Failed: 0.180000000 INFO /racecar_spawn [gazebo_interface.py:31(spawn_urdf_model_client)] [topics: /clock, /rosout] Calling service /gazebo/spawn_urdf_model
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/include/gazebo_plugins/gazebo_ros_utils.h:99(__cxx11::string gazebo::GetRobotNamespace)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Laser Plugin: Using the 'robotNamespace' param: '/'
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_laser.cpp:111(GazeboRosLaser::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Starting Laser Plugin (ns = /)
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_laser.cpp:135(GazeboRosLaser::LoadThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Laser Plugin (ns = /)  <tf_prefix_>, set to ""
ROS Log Match Failed: 0.372000000 INFO /racecar_spawn [gazebo_interface.py:33(spawn_urdf_model_client)] [topics: /clock, /rosout] Spawn status: SpawnModel: Successfully spawned entity
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/include/gazebo_plugins/gazebo_ros_utils.h:99(__cxx11::string gazebo::GetRobotNamespace)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan] Camera Plugin: Using the 'robotNamespace' param: '/'
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_camera_utils.cpp:305(GazeboRosCameraUtils::LoadThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan] Camera Plugin (ns = /)  <tf_prefix_>, set to ""
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:62(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] Loading gazebo_ros_control plugin
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:161(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] Starting gazebo_ros_control plugin in namespace: /racecar
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:280(__cxx11::string gazebo_ros_control::GazeboRosControlPlugin::getURDF)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:207(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates, /camera/zed/rgb/image_rect_color/compressed, /camera/zed/rgb/image_rect_color/compressed/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressed/parameter_updates, /camera/zed/rgb/image_rect_color, /camera/zed/rgb/image_rect_color/theora, /camera/zed/rgb/image_rect_color/theora/parameter_descriptions, /camera/zed/rgb/image_rect_color/theora/parameter_updates, /camera/zed/rgb/camera_info] Loaded gazebo_ros_control.
ROS Log Match Failed: 27.232000000 INFO /vesc/low_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/nodelet.cpp:159(unloadNodelet)] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux_nodelet_manager/bond] Unloading nodelet /vesc/low_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager
ROS Log Match Failed: 27.234000000 INFO /vesc/high_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/nodelet.cpp:159(unloadNodelet)] [topics: /rosout, /vesc/high_level/ackermann_cmd_mux_nodelet_manager/bond] Unloading nodelet /vesc/high_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager
ROS Log Match Failed: [0m[ INFO] [1619938429.183973236]: Initializing nodelet with 4 worker threads.[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.367919012]: AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/high_level_mux.yaml][0m
ROS Log Match Failed: [0m[ INFO] [1619938429.156338508]: Loading nodelet /vesc/low_level/ackermann_cmd_mux of type ackermann_cmd_mux/AckermannCmdMuxNodelet to manager ackermann_cmd_mux_nodelet_manager with the following remappings:[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.193106278]: waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] has not been advertised, waiting...[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.244382005]: waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.[0m
ROS Log Match Failed: [0m[ INFO] [1619938463.946905647, 27.232000000]: Unloading nodelet /vesc/low_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager[0m
Insert Row to Table ROSLog Failed
Insert Row to Table ROSLog Failed
Insert Row to Table ROSLog Failed
Insert Row to Table ROSLog Failed
ROS Log Match Failed: [0m[ INFO] [1619938431.700792706]: advertised as /pf/pose/odom
ROS Log Match Failed: [0m
ROS Log Match Failed: [0m[ INFO] [1619938429.085168513]: Loading nodelet /vesc/high_level/ackermann_cmd_mux of type ackermann_cmd_mux/AckermannCmdMuxNodelet to manager ackermann_cmd_mux_nodelet_manager with the following remappings:[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.119763657]: waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] has not been advertised, waiting...[0m
ROS Log Match Failed: [0m[ INFO] [1619938429.213748362]: waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.[0m
ROS Log Match Failed: [0m[ INFO] [1619938463.951026289, 27.234000000]: Unloading nodelet /vesc/high_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager[0m
Insert Row to Table ROSLog Failed
Insert Row to Table ROSLog Failed
ROS Log Match Failed: Connect Mysql log success
ROS Log Match Failed: Create Table ROSLog Success
ROS Log Match Failed: Create Table ROSLog Success
ROS Log Match Failed: Starting Parse ROS Log
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938430.070822262]: advertised as /vesc/low_level/ackermann_cmd_mux/input/navigation
ROS Log Match Failed: ROS Log Match Failed: [0m
ROS Log Match Failed: ROS Log Match Failed: Press Ctrl-C to interrupt
ROS Log Match Failed: ROS Log Match Failed: log file: /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/racecar_spawn-4*.log
ROS Log Match Failed: ROS Log Match Failed: log file: /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/keyboard_teleop-19*.log
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.209254195]: Initializing nodelet with 4 worker threads.[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.321988522]: AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/low_level_mux.yaml][0m
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 562, in connect
ROS Log Match Failed: ROS Log Match Failed:     self.read_header()
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 657, in read_header
ROS Log Match Failed: ROS Log Match Failed:     self._validate_header(read_ros_handshake_header(sock, self.read_buff, self.protocol.buff_size))
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosgraph/network.py", line 357, in read_ros_handshake_header
ROS Log Match Failed: ROS Log Match Failed:     d = sock.recv(buff_size)
ROS Log Match Failed: ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed: 0.000000000  Node Startup
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout] waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/low_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout] waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux_nodelet_manager [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/loader.cpp:233(Loader::Impl::advertiseRosApi)] [topics: /rosout] Initializing nodelet with 4 worker threads.
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/high_level/ackermann_cmd_mux_nodelet_manager [/home/liike/ROS/src/racecar/system/racecar/ackermann_cmd_mux/src/ackermann_cmd_mux_nodelet.cpp:181(AckermannCmdMuxNodelet::reloadConfiguration)] [topics: /rosout, /vesc/high_level/ackermann_cmd_mux/parameter_descriptions, /vesc/high_level/ackermann_cmd_mux/parameter_updates, /vesc/high_level/ackermann_cmd_mux/output] AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/high_level_mux.yaml]
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/low_level/ackermann_cmd_mux_nodelet_manager [/home/liike/ROS/src/racecar/system/racecar/ackermann_cmd_mux/src/ackermann_cmd_mux_nodelet.cpp:181(AckermannCmdMuxNodelet::reloadConfiguration)] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux/parameter_descriptions, /vesc/low_level/ackermann_cmd_mux/parameter_updates, /vesc/low_level/ackermann_cmd_mux/output] AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/low_level_mux.yaml]
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /vesc/mux_chainer [/tmp/binarydeb/ros-melodic-topic-tools-1.14.10/src/relay.cpp:101(MessageEvent<topic_tools::ShapeShifter>&))] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux/input/navigation] advertised as /vesc/low_level/ackermann_cmd_mux/input/navigation
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:80(service::exists)] [topics: /rosout] waitForService: Service [/gazebo/set_physics_properties] has not been advertised, waiting...
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /gazebo_gui [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:80(service::exists)] [topics: /rosout] waitForService: Service [/gazebo_gui/set_physics_properties] has not been advertised, waiting...
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /racecar_spawn [gazebo_interface.py:27(spawn_urdf_model_client)] [topics: /clock, /rosout] Waiting for service /gazebo/spawn_urdf_model
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-roscpp-1.14.10/src/libros/service.cpp:123(service::waitForService)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states] waitForService: Service [/gazebo/set_physics_properties] is now available.
ROS Log Match Failed: ROS Log Match Failed: 0.019000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-2.8.7/src/gazebo_ros_api_plugin.cpp:2334(GazeboRosApiPlugin::physicsReconfigureThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Physics dynamic reconfigure ready.
ROS Log Match Failed: ROS Log Match Failed: 0.000000000 INFO /better_odom [/tmp/binarydeb/ros-melodic-topic-tools-1.14.10/src/relay.cpp:101(MessageEvent<topic_tools::ShapeShifter>&))] [topics: /rosout, /pf/pose/odom] advertised as /pf/pose/odom
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed: 0.180000000 INFO /racecar_spawn [gazebo_interface.py:31(spawn_urdf_model_client)] [topics: /clock, /rosout] Calling service /gazebo/spawn_urdf_model
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/include/gazebo_plugins/gazebo_ros_utils.h:99(__cxx11::string gazebo::GetRobotNamespace)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Laser Plugin: Using the 'robotNamespace' param: '/'
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_laser.cpp:111(GazeboRosLaser::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Starting Laser Plugin (ns = /)
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_laser.cpp:135(GazeboRosLaser::LoadThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates] Laser Plugin (ns = /)  <tf_prefix_>, set to ""
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /racecar_spawn [gazebo_interface.py:33(spawn_urdf_model_client)] [topics: /clock, /rosout] Spawn status: SpawnModel: Successfully spawned entity
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/include/gazebo_plugins/gazebo_ros_utils.h:99(__cxx11::string gazebo::GetRobotNamespace)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan] Camera Plugin: Using the 'robotNamespace' param: '/'
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-plugins-2.8.7/src/gazebo_ros_camera_utils.cpp:305(GazeboRosCameraUtils::LoadThread)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan] Camera Plugin (ns = /)  <tf_prefix_>, set to ""
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:62(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] Loading gazebo_ros_control plugin
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:161(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] Starting gazebo_ros_control plugin in namespace: /racecar
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:280(__cxx11::string gazebo_ros_control::GazeboRosControlPlugin::getURDF)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates] gazebo_ros_control plugin is waiting for model URDF in parameter [/robot_description] on the ROS param server.
ROS Log Match Failed: ROS Log Match Failed: 0.372000000 INFO /gazebo [/tmp/binarydeb/ros-melodic-gazebo-ros-control-2.8.7/src/gazebo_ros_control_plugin.cpp:207(GazeboRosControlPlugin::Load)] [topics: /rosout, /clock, /gazebo/link_states, /gazebo/model_states, /gazebo/parameter_descriptions, /gazebo/parameter_updates, /scan, /camera/zed/parameter_descriptions, /camera/zed/parameter_updates, /camera/zed/rgb/image_rect_color/compressedDepth, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressedDepth/parameter_updates, /camera/zed/rgb/image_rect_color/compressed, /camera/zed/rgb/image_rect_color/compressed/parameter_descriptions, /camera/zed/rgb/image_rect_color/compressed/parameter_updates, /camera/zed/rgb/image_rect_color, /camera/zed/rgb/image_rect_color/theora, /camera/zed/rgb/image_rect_color/theora/parameter_descriptions, /camera/zed/rgb/image_rect_color/theora/parameter_updates, /camera/zed/rgb/camera_info] Loaded gazebo_ros_control.
ROS Log Match Failed: ROS Log Match Failed: 27.232000000 INFO /vesc/low_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/nodelet.cpp:159(unloadNodelet)] [topics: /rosout, /vesc/low_level/ackermann_cmd_mux_nodelet_manager/bond] Unloading nodelet /vesc/low_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager
ROS Log Match Failed: ROS Log Match Failed: 27.234000000 INFO /vesc/high_level/ackermann_cmd_mux [/tmp/binarydeb/ros-melodic-nodelet-1.9.16/src/nodelet.cpp:159(unloadNodelet)] [topics: /rosout, /vesc/high_level/ackermann_cmd_mux_nodelet_manager/bond] Unloading nodelet /vesc/high_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.183973236]: Initializing nodelet with 4 worker threads.[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.367919012]: AckermannCmdMux : (re)configured [/home/liike/ROS/src/racecar/system/racecar/racecar/config/racecar-v2/high_level_mux.yaml][0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.156338508]: Loading nodelet /vesc/low_level/ackermann_cmd_mux of type ackermann_cmd_mux/AckermannCmdMuxNodelet to manager ackermann_cmd_mux_nodelet_manager with the following remappings:[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.193106278]: waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] has not been advertised, waiting...[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.244382005]: waitForService: Service [/vesc/low_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938463.946905647, 27.232000000]: Unloading nodelet /vesc/low_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager[0m
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938431.700792706]: advertised as /pf/pose/odom
ROS Log Match Failed: ROS Log Match Failed: [0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.085168513]: Loading nodelet /vesc/high_level/ackermann_cmd_mux of type ackermann_cmd_mux/AckermannCmdMuxNodelet to manager ackermann_cmd_mux_nodelet_manager with the following remappings:[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.119763657]: waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] has not been advertised, waiting...[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938429.213748362]: waitForService: Service [/vesc/high_level/ackermann_cmd_mux_nodelet_manager/load_nodelet] is now available.[0m
ROS Log Match Failed: ROS Log Match Failed: [0m[ INFO] [1619938463.951026289, 27.234000000]: Unloading nodelet /vesc/high_level/ackermann_cmd_mux from manager ackermann_cmd_mux_nodelet_manager[0m
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: Insert Row to Table ROSLog Failed
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
ROS Log Match Failed: ROS Log Match Failed:     self.stat_bytes += recv_buff(sock, b, p.buff_size)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 104, in recv_buff
ROS Log Match Failed: ROS Log Match Failed:     d = sock.recv(buff_size)
ROS Log Match Failed: ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed: Press q to quit
ROS Log Match Failed: ROS Log Match Failed: logging to /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/rosout.log
ROS Log Match Failed: ROS Log Match Failed: re-publishing aggregated messages to /rosout_agg
ROS Log Match Failed: ROS Log Match Failed: subscribed to /rosout
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 177, in validated_f
ROS Log Match Failed: ROS Log Match Failed:     code, msg, val = f(*newArgs, **kwds)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 435, in searchParam
ROS Log Match Failed: ROS Log Match Failed:     search_key = self.param_server.search_param(caller_id, key)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/paramserver.py", line 116, in search_param
ROS Log Match Failed: ROS Log Match Failed:     raise ValueError("namespace must be global")
ROS Log Match Failed: ROS Log Match Failed: ValueError: namespace must be global
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed: ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed: ROS Log Match Failed:     return u.close()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed: ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed: ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed: ROS Log Match Failed:     return u.close()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed: ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed: ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed: ROS Log Match Failed:     return u.close()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed: ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed: ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed: ROS Log Match Failed:     return u.close()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed: ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
ROS Log Match Failed: ROS Log Match Failed:     self.send_content(h, request_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
ROS Log Match Failed: ROS Log Match Failed:     connection.endheaders(request_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
ROS Log Match Failed: ROS Log Match Failed:     self._send_output(message_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
ROS Log Match Failed: ROS Log Match Failed:     self.send(msg)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 860, in send
ROS Log Match Failed: ROS Log Match Failed:     self.connect()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 837, in connect
ROS Log Match Failed: ROS Log Match Failed:     self.timeout, self.source_address)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
ROS Log Match Failed: ROS Log Match Failed:     raise err
ROS Log Match Failed: ROS Log Match Failed: error: [Errno 111] Connection refused
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed: ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed: ROS Log Match Failed:     return u.close()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed: ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed: ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed: ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed: ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed: ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed: ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed: ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
ROS Log Match Failed: ROS Log Match Failed:     self.send_content(h, request_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
ROS Log Match Failed: ROS Log Match Failed:     connection.endheaders(request_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
ROS Log Match Failed: ROS Log Match Failed:     self._send_output(message_body)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
ROS Log Match Failed: ROS Log Match Failed:     self.send(msg)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 860, in send
ROS Log Match Failed: ROS Log Match Failed:     self.connect()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 837, in connect
ROS Log Match Failed: ROS Log Match Failed:     self.timeout, self.source_address)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
ROS Log Match Failed: ROS Log Match Failed:     raise err
ROS Log Match Failed: ROS Log Match Failed: error: [Errno 111] Connection refused
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
ROS Log Match Failed: ROS Log Match Failed:     self.finish_request(request, client_address)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
ROS Log Match Failed: ROS Log Match Failed:     self.RequestHandlerClass(request, client_address, self)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
ROS Log Match Failed: ROS Log Match Failed:     self.handle()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
ROS Log Match Failed: ROS Log Match Failed:     self.handle_one_request()
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
ROS Log Match Failed: ROS Log Match Failed:     self.raw_requestline = self.rfile.readline(65537)
ROS Log Match Failed: ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 480, in readline
ROS Log Match Failed: ROS Log Match Failed:     data = self._sock.recv(self._rbufsize)
ROS Log Match Failed: ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: ROS Log Match Failed: 
ROS Log Match Failed: Computing Problem Spotlight
ROS Log Match Failed: Create Table ROSMsg Success
ROS Log Match Failed: Unrecognized Priority: WARNING
ROS Log Match Failed: Mysql DisConnect
ROS Log Match Failed: Using Augeas to Parse Configuration File
ROS Log Match Failed: Extract key-value Finished
ROS Log Match Failed: Extract Env Finished
ROS Log Match Failed: Connect Database wise success
ROS Log Match Failed: Giving Problem Spotlight and Resolve Spotlight
ROS Log Match Failed: Problem Spotlight No.0 : Traceback (most recent call last):
ROS Log Match Failed: Problem Spotlight No.1 : [gazebo_gui-3] escalating to SIGTERM
ROS Log Match Failed: Problem Spotlight No.2 : [gazebo-2] escalating to SIGTERM
ROS Log Match Failed: Problem Spotlight No.3 : ERROR: cannot launch node of type [controller_manager/spawn]: Cannot locate node of type [spawn] in package [controller_manager]. Make sure file exists in package path and permission is set to executable (chmod +x)
ROS Log Match Failed: Suspicious word:    controller_manager    with key:    Conf: controller_manager    and value:    controller_manager spawn false screen /racecar left_rear_wheel_velocity_controller right_rear_wheel_velocity_controller\n                                            left_front_wheel_velocity_controller right_front_wheel_velocity_controller\n                                            left_steering_hinge_position_controller right_steering_hinge_position_controller\n                                            joint_state_controller
ROS Log Match Failed: Problem Spotlight No.4 : Cannot locate node of type [spawn] in package [controller_manager]. Make sure file exists in package path and permission is set to executable (chmod +x)
ROS Log Match Failed: Problem Spotlight No.5 : stopping master...
ROS Log Match Failed: Problem Spotlight No.6 : keyboard interrupt, will exit
ROS Log Match Failed: Problem Spotlight No.7 : -CACHEDPARAM [/rosout/omit_topics] by /rosout
ROS Log Match Failed: FilePath:    /rosout/omit_topics    not Exist
ROS Log Match Failed: FilePath:    /rosout    not Exist
ROS Log Match Failed: Problem Spotlight No.8 : -SERVICE [/rosout/set_logger_level] /rosout rosrpc://ubuntu:53689
ROS Log Match Failed: FilePath:    /rosout/set_logger_level    not Exist
ROS Log Match Failed: FilePath:    //ubuntu    not Exist
ROS Log Match Failed: Problem Spotlight No.9 : -SERVICE [/rosout/get_loggers] /rosout rosrpc://ubuntu:53689
ROS Log Match Failed: FilePath:    /rosout/get_loggers    not Exist
ROS Log Match Failed: Mysql DisConnect
Insert Row to Table ROSLog Failed
Insert Row to Table ROSLog Failed
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 737, in receive_once
ROS Log Match Failed:     self.stat_bytes += recv_buff(sock, b, p.buff_size)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 104, in recv_buff
ROS Log Match Failed:     d = sock.recv(buff_size)
ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: 
ROS Log Match Failed: Press q to quit
ROS Log Match Failed: logging to /home/liike/.ros/log/24e1b228-ab13-11eb-8440-000c29637311/rosout.log
ROS Log Match Failed: re-publishing aggregated messages to /rosout_agg
ROS Log Match Failed: subscribed to /rosout
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 177, in validated_f
ROS Log Match Failed:     code, msg, val = f(*newArgs, **kwds)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 435, in searchParam
ROS Log Match Failed:     search_key = self.param_server.search_param(caller_id, key)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/paramserver.py", line 116, in search_param
ROS Log Match Failed:     raise ValueError("namespace must be global")
ROS Log Match Failed: ValueError: namespace must be global
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed:     return u.close()
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed:     return u.close()
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed:     return u.close()
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed:     return u.close()
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
ROS Log Match Failed:     self.send_content(h, request_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
ROS Log Match Failed:     connection.endheaders(request_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
ROS Log Match Failed:     self._send_output(message_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
ROS Log Match Failed:     self.send(msg)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 860, in send
ROS Log Match Failed:     self.connect()
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 837, in connect
ROS Log Match Failed:     self.timeout, self.source_address)
ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
ROS Log Match Failed:     raise err
ROS Log Match Failed: error: [Errno 111] Connection refused
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1316, in single_request
ROS Log Match Failed:     return self.parse_response(response)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1493, in parse_response
ROS Log Match Failed:     return u.close()
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 800, in close
ROS Log Match Failed:     raise Fault(**self._stack[0])
ROS Log Match Failed: Fault: <Fault -1: 'publisherUpdate: unknown method name'>
ROS Log Match Failed: 
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/threadpool.py", line 218, in run
ROS Log Match Failed:     result = cmd(*args)
ROS Log Match Failed:   File "/opt/ros/melodic/lib/python2.7/dist-packages/rosmaster/master_api.py", line 210, in publisher_update_task
ROS Log Match Failed:     ret = xmlrpcapi(api).publisherUpdate('/master', topic, pub_uris)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1243, in __call__
ROS Log Match Failed:     return self.__send(self.__name, args)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1602, in __request
ROS Log Match Failed:     verbose=self.__verbose
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1283, in request
ROS Log Match Failed:     return self.single_request(host, handler, request_body, verbose)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1311, in single_request
ROS Log Match Failed:     self.send_content(h, request_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/xmlrpclib.py", line 1459, in send_content
ROS Log Match Failed:     connection.endheaders(request_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 1095, in endheaders
ROS Log Match Failed:     self._send_output(message_body)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 898, in _send_output
ROS Log Match Failed:     self.send(msg)
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 860, in send
ROS Log Match Failed:     self.connect()
ROS Log Match Failed:   File "/usr/lib/python2.7/httplib.py", line 837, in connect
ROS Log Match Failed:     self.timeout, self.source_address)
ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 575, in create_connection
ROS Log Match Failed:     raise err
ROS Log Match Failed: error: [Errno 111] Connection refused
ROS Log Match Failed: 
ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 599, in process_request_thread
ROS Log Match Failed:     self.finish_request(request, client_address)
ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 334, in finish_request
ROS Log Match Failed:     self.RequestHandlerClass(request, client_address, self)
ROS Log Match Failed:   File "/usr/lib/python2.7/SocketServer.py", line 655, in __init__
ROS Log Match Failed:     self.handle()
ROS Log Match Failed:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 342, in handle
ROS Log Match Failed:     self.handle_one_request()
ROS Log Match Failed:   File "/usr/lib/python2.7/BaseHTTPServer.py", line 310, in handle_one_request
ROS Log Match Failed:     self.raw_requestline = self.rfile.readline(65537)
ROS Log Match Failed:   File "/usr/lib/python2.7/socket.py", line 480, in readline
ROS Log Match Failed:     data = self._sock.recv(self._rbufsize)
ROS Log Match Failed: error: [Errno 104] Connection reset by peer
ROS Log Match Failed: 
Computing Problem Spotlight
Create Table ROSMsg Success
Unrecognized Priority: WARNING
Mysql DisConnect
Using Augeas to Parse Configuration File
Extract key-value Finished
Extract Env Finished
Connect Database wise success
Giving Problem Spotlight and Resolve Spotlight
Problem Spotlight No.0 : 2021-05-02 14:54:39 Error Traceback (most recent call last):
Problem Spotlight No.1 : 2021-05-02 14:54:39 Error [gazebo_gui-3] escalating to SIGTERM
Problem Spotlight No.2 : 2021-05-02 14:54:39 Error [gazebo-2] escalating to SIGTERM
Problem Spotlight No.3 : 2021-05-02 14:53:48 Error ERROR: cannot launch node of type [controller_manager/spawn]: Cannot locate node of type [spawn] in package [controller_manager]. Make sure file exists in package path and permission is set to executable (chmod +x)
Suspicious word:    spawn    with key:    Conf: controller_manager    and value:    spawn
Suspicious word:    controller_manager    with key:    Conf: controller_manager    and value:    controller_manager spawn false screen /racecar left_rear_wheel_velocity_controller right_rear_wheel_velocity_controller\n                                            left_front_wheel_velocity_controller right_front_wheel_velocity_controller\n                                            left_steering_hinge_position_controller right_steering_hinge_position_controller\n                                            joint_state_controller
Problem Spotlight No.4 : 2021-05-02 14:53:48 Error Cannot locate node of type [spawn] in package [controller_manager]. Make sure file exists in package path and permission is set to executable (chmod +x)
Problem Spotlight No.5 : 2021-05-02 14:54:39 Note stopping master...
Problem Spotlight No.6 : 2021-05-02 14:54:39 Note keyboard interrupt, will exit
Problem Spotlight No.7 : 2021-05-02 14:54:39 Note -CACHEDPARAM [/rosout/omit_topics] by /rosout
FilePath:    /rosout    not Exist
Problem Spotlight No.8 : 2021-05-02 14:54:39 Note -SERVICE [/rosout/set_logger_level] /rosout rosrpc://ubuntu:53689
Problem Spotlight No.9 : 2021-05-02 14:54:39 Note -SERVICE [/rosout/get_loggers] /rosout rosrpc://ubuntu:53689
Mysql DisConnect
Time Using: 3.16965 s
