[rospy.client][INFO] 2021-05-18 16:22:20,307: init_node, name[/gazebo_odometry_node], pid[93693]
[xmlrpc][INFO] 2021-05-18 16:22:20,307: XML-RPC server binding to 0.0.0.0:0
[xmlrpc][INFO] 2021-05-18 16:22:20,308: Started XML-RPC server [http://ubuntu:45383/]
[rospy.impl.masterslave][INFO] 2021-05-18 16:22:20,308: _ready: http://ubuntu:45383/
[rospy.init][INFO] 2021-05-18 16:22:20,309: ROS Slave URI: [http://ubuntu:45383/]
[xmlrpc][INFO] 2021-05-18 16:22:20,309: xml rpc node: starting XML-RPC server
[rospy.registration][INFO] 2021-05-18 16:22:20,309: Registering with master node http://localhost:11311
[rospy.registration][INFO] 2021-05-18 16:22:20,310: Registering publisher topic [/vesc/odom] type [nav_msgs/Odometry] with master
[rospy.init][INFO] 2021-05-18 16:22:20,410: registered with master
[rospy.rosout][INFO] 2021-05-18 16:22:20,410: initializing /rosout core topic
[rospy.rosout][INFO] 2021-05-18 16:22:20,411: connected to core topic /rosout
[rospy.simtime][INFO] 2021-05-18 16:22:20,412: initializing /clock core topic
[rospy.simtime][INFO] 2021-05-18 16:22:20,415: connected to core topic /clock
[rospy.internal][INFO] 2021-05-18 16:22:20,520: topic[/rosout] adding connection to [/rosout], count 0
[rospy.internal][INFO] 2021-05-18 16:22:20,521: topic[/vesc/odom] adding connection to [/better_odom], count 0
[rospy.internal][INFO] 2021-05-18 16:22:22,758: topic[/gazebo/link_states] adding connection to [http://ubuntu:44103/], count 0
[rospy.internal][INFO] 2021-05-18 16:22:22,760: topic[/clock] adding connection to [http://ubuntu:44103/], count 0
[rospy.internal][INFO] 2021-05-18 16:22:37,910: topic[/vesc/odom] removing connection to /better_odom
[rospy.core][INFO] 2021-05-18 16:22:37,939: signal_shutdown [signal-2]
[rospy.internal][INFO] 2021-05-18 16:22:37,955: topic[/rosout] removing connection to /rosout
[rospy.internal][INFO] 2021-05-18 16:22:37,961: topic[/clock] removing connection to http://ubuntu:44103/
[rospy.internal][INFO] 2021-05-18 16:22:37,961: topic[/gazebo/link_states] removing connection to http://ubuntu:44103/
[rospy.impl.masterslave][INFO] 2021-05-18 16:22:37,961: signal-2
[rospy.internal][ERROR] 2021-05-18 16:22:37,962: Traceback (most recent call last):
  File "/opt/ros/melodic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 732, in receive_once
    sock.setblocking(1)
  File "/usr/lib/python2.7/socket.py", line 228, in meth
    return getattr(self._sock,name)(*args)
  File "/usr/lib/python2.7/socket.py", line 174, in _dummy
    raise error(EBADF, 'Bad file descriptor')
error: [Errno 9] Bad file descriptor

[rospy.core][INFO] 2021-05-18 16:22:38,580: signal_shutdown [atexit]
